export const CHANGE_CATEGORRY = "CHANGE_CATEGORRY";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";

export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const ADD_TO_CART = "ADD_TO_CART";


export const REMOCE_FROM_CART = "REMOCE_FROM_CART";
export const CREACTE_PRODUCT_SUCCESS="CREACTE_PRODUCT_SUCCESS"
export const UPDATE_PRODUCT_SUCCESS="UPDATE_PRODUCT_SUCCESS"